version: "3.8"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
  php:
    build: .
    volumes:
      - ./code:/code
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: web
      
  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
         - 8081:80
        environment:
          - MYSQL_ROOT_PASSWORD:secret
          - PMA_HOST:mysql
          - MYSQL_USERNAME:root
        depends_on:
         - db